name: Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

env:
  GOPRIVATE: github.com/upsun/lib-sun

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run config private repo
      env:
        TOKEN: ${{ secrets.MICK_GITHUB_TOKEN }}
      run: git config --global url."https://user:${TOKEN}@github.com".insteadOf https://github.com
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: "./cmd/"
        build_flags: -v
        ldflags:  -X "version.VERSION=${{ GITHUB_REF_NAME }}"
        # -X "main.buildTime=${{ env.BUILD_TIME }}" -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}
        extra_files: LICENSE README.md